### ISSUE TITLE
Not an issue but a question re time periods

### ISSUE THREAD

**Issue by DaTrader** [elixir-cldr/cldr_dates_times#29]
Hey Kip,

looking at the API over and over again, I can't seem to find a way to format a duration (a time period) regardless of when it starts or ends e.g.:

2 days
3 weeks
2 quarters

Can you help with this one?

Thanks,

Damir

**Comment by kipcole9** [comment]
[ex_cldr_units](https://hex.pm/packages/ex_cldr_units) is (mostly) your friend here.  These are considered as `time units` with the emphasis on `unit` which is why they occur in that particular library.  Some examples:
```elixir
iex> MyApp.Cldr.Unit.to_string Cldr.Unit.new!(2, :week)
{:ok, "2 weeks"}

iex> MyApp.Cldr.Unit.to_string Cldr.Unit.new!(2, :week), locale: "fr"
{:ok, "2 semaines"}
```
At present, CLDR knows about the following time units:
```elixir
iex> Cldr.Unit.known_units_by_category |> Map.get(:duration)
[:century, :day, :decade, :hour, :microsecond, :millisecond, :minute, :month,
 :nanosecond, :second, :week, :year]
```
Which means that `:quarter` isn't a known unit unfortunately.  I will submit a [ticket](https://unicode-org.atlassian.net/jira/software/c/projects/CLDR/issues) to CLDR but I wouldn't expect a quick outcome. 

As an aside, in [ex_cldr_calendars](https://hex.pm/packages/ex_cldr_calendars) there is a module [Cldr.Calendar.Duration](https://hexdocs.pm/ex_cldr_calendars/Cldr.Calendar.Duration.html) that will calculate the difference between two dates/date_times and it will also use `Cldr.Unit.to_string/1` for formatting if `ex_cldr_units` is configured.  For example:
```elixir
iex> {:ok, duration} = Cldr.Calendar.Duration.new(~D[2020-10-19], ~D[2021-12-01])
{:ok,
 %Cldr.Calendar.Duration{
   day: 13,
   hour: 0,
   microsecond: 0,
   minute: 0,
   month: 1,
   second: 0,
   year: 1
 }}
iex> Cldr.Calendar.Duration.to_string(duration)                                  
{:ok, "1 year, 1 month, and 13 days"}
```

**Comment by DaTrader** [comment]
Thanks, Kip!

Just so you know that little by little your libraries are becoming invaluable to my app.

**Comment by kipcole9** [comment]
Thanks for the encouragement, definitely helps with motivation to know the work is useful!

**Comment by DaTrader** [comment]
Kip, just to let you known I'm getting the following warning when compiling the deps (I'm still on Elixir 1.10.3).

```
warning: Date.to_gregorian_days/1 is undefined or private
  lib/cldr/calendar/behaviour.ex:6: Cldr.Calendar.Behaviour.__using__/1
```

And Merry Christmas.
